---
# tasks file for ec2
- name: Installing boto & boto3 on local system
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ python_pkgs }}"

- name: Creating Security Group for K8s Cluster
  ec2_group:
    name: "{{ sg_name }}"
    description: "{{ sg_description }}"
    region: "{{ region_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: all
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0

- name: Create an EC2 key
  ec2_key:
    aws_access_key: "{{ access_key }}"
    aws_secret_key:  "{{ secret_key }}"
    name: "ACM-key"
    region: "{{ region_name }}"
  register: ec2_key_result

- name: Save private key (PEM file)
  copy: content="{{ec2_key_result.key.private_key}}" dest=/root/aws-ansible/ACM-key.pem  mode=0600
  when: ec2_key_result.changed

- name: Launching 4 EC2 instances on AWS
  ec2:
    key_name: ACM-key
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: true
    group: "{{ sg_name }}"
    count: 1
    vpc_subnet_id: "{{ subnet_name }}"
    assign_public_ip: yes
    region: "{{ region_name }}"
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_tags:
      Name: "{{ item }}"
  register: ec2
  loop: "{{ instance_tag }}"

- name: Add 1st instance to host group ec2_master
  add_host:
    hostname: "{{ ec2.results[0].instances[0].public_ip }}"
    groupname: ec2_master

- name: Add 2nd instance to host group ec2_nodes
  add_host:
    hostname: "{{ ec2.results[1].instances[0].public_ip }}"
    groupname: ec2_nodes

- name: Add 3rd instance to host group ec2_nodes
  add_host:
    hostname: "{{ ec2.results[2].instances[0].public_ip }}"
    groupname: ec2_nodes

- name: Add 4rd instance to host group ec2_nodes
  add_host:
    hostname: "{{ ec2.results[3].instances[0].public_ip }}"
    groupname: ec2_nodes

- name: Wait for SSH to come up
  wait_for:
    host: "{{ ec2.results[3].instances[0].public_dns_name }}"
    port: 22
    state: started
